import logging
import re
from pathlib import Path
from typing import Any, Dict, List, Optional

from fixers.brace_utils import count_braces_safe

logger = logging.getLogger(__name__)

# Попытка импорта Tree-sitter
try:
    from fixers.rust_tree_sitter import RustTreeSitter
    HAS_TREE_SITTER = True
except ImportError:
    HAS_TREE_SITTER = False


class RustSyntaxHealer:
    """Read-only анализатор, предлагающий исправления синтаксиса Rust."""

    def __init__(self, dry_run: bool = False):
        self.dry_run = dry_run

    def analyze_and_suggest(
        self,
        error: Dict,
        file_path: Path,
        llm_client=None,
        invariant_guard=None,
        segmenter=None,
    ) -> List[Dict[str, Any]]:
        code = error.get("code", "")
        msg = error.get("message", "").lower()
        line_num = error.get("line", 0)
        error_text = error.get("message", "")

        if any(kw in msg for kw in ("unclosed", "unexpected", "duplicate")):
            return self._structural_suggestions(error, file_path)

        if code == "E0765" or "unterminated" in msg or ("unclosed" in msg and "quote" in msg):
            return self._unclosed_quote_suggestions(error, file_path)

        if "expected `}`" in msg:
            return self._missing_brace_suggestions(error, file_path)

        if "unexpected closing delimiter" in msg and "`}`" in error_text:
            return self._unexpected_closing_brace_suggestions(error, file_path)

        if "expected `{`" in msg:
            return self._missing_open_brace_suggestions(error, file_path)

        if "different indentation" in msg:
            return self._indentation_mismatch_suggestions(error, file_path)

        if "unknown" in msg and "prefix" in msg:
            return self._unknown_prefix_suggestions(error, file_path, line_num)

        if code == "E0001" or "expected ';'" in msg:
            return self._missing_semicolon_suggestions(error, file_path, line_num)

        return []

    def _unclosed_quote_suggestions(self, error: Dict, file_path: Path) -> List[Dict]:
        lines = self._read_file_lines(file_path)
        line_num = error.get("line", 0)
        if not line_num or line_num > len(lines):
            return []

        for offset in range(5):
            idx = line_num - 1 + (offset - 2)
            if 0 <= idx < len(lines):
                if lines[idx].count('"') % 2 != 0:
                    fixed_line = lines[idx].rstrip('\n').rstrip('\r') + '"\n'
                    patch = (
                        f"--- a/main.rs\n"
                        f"+++ b/main.rs\n"
                        f"@@ -{idx+1},1 +{idx+1},1 @@\n"
                        f"-{lines[idx]}"
                        f"+{fixed_line}"
                    )
                    return [{
                        "type": "unclosed_quote",
                        "line": idx + 1,
                        "content": f"Line {idx+1} appears to be missing a closing quote. Add '\"' at the end.",
                        "patch": patch,
                    }]
        return []

    def _structural_suggestions(self, error: Dict, file_path: Path) -> List[Dict]:
        content = self._read_file(file_path)
        lines = content.splitlines(keepends=True)
        suggestions = []

        # 1) Tree-sitter: генерация сбалансированного кода
        if HAS_TREE_SITTER:
            try:
                ts = RustTreeSitter()
                balanced = ts.generate_balanced_code(content)
                if balanced and balanced != content:
                    suggestions.append({
                        "type": "brace_balance_by_treesitter",
                        "line": 1,
                        "content": "Tree-sitter generated a balanced version of the file.",
                        "balanced_content": balanced,
                    })
                    return suggestions
            except Exception as e:
                logger.debug("Tree-sitter balanced code generation failed: %s", e)

        # 2) Fallback: эвристика по отступам
        safe_open, safe_close = count_braces_safe(content)
        diff = safe_open - safe_close
        if diff != 0:
            balanced_lines = self._balance_braces_by_indent(lines)
            suggestions.append({
                "type": "brace_balance_by_indent",
                "line": 1,
                "content": (
                    f"File has {safe_open} opening braces but {safe_close} closing braces. "
                    f"A balanced version was generated by analysing indentation levels."
                ),
                "patch": None,
                "balanced_content": "".join(balanced_lines) if balanced_lines else content,
            })
        return suggestions

    # ------------------------------------------------------------------
    # ИСПРАВЛЕННЫЙ АЛГОРИТМ БАЛАНСИРОВКИ СКОБОК
    # ------------------------------------------------------------------
    def _balance_braces_by_indent(self, lines: List[str]) -> List[str]:
        """
        Вставляет недостающие закрывающие скобки с правильным отступом
        и удаляет явно лишние закрывающие скобки.
        """
        # 1. Собираем карту скобок: (line_index, indent, is_open)
        braces = []
        for idx, line in enumerate(lines):
            stripped = line.lstrip()
            if stripped.startswith('//') or stripped.startswith('*'):
                continue
            indent = len(line) - len(line.lstrip())
            for ch in line:
                if ch == '{':
                    braces.append((idx, indent, True))
                elif ch == '}':
                    braces.append((idx, indent, False))

        # 2. Стек для ожидаемых закрытий (индекс открывающей)
        stack = []
        to_remove = set()

        for i, (idx, indent, is_open) in enumerate(braces):
            if is_open:
                stack.append(i)
            else:
                if not stack:
                    to_remove.add(idx)
                else:
                    matched = None
                    for j in reversed(stack):
                        if braces[j][1] == indent:
                            matched = j
                            break
                    if matched is not None:
                        stack.remove(matched)
                    else:
                        to_remove.add(idx)

        # 3. Удаляем лишние закрывающие скобки
        result_lines = [line for i, line in enumerate(lines) if i not in to_remove]

        # 4. Вставляем недостающие закрывающие для оставшихся в стеке
        for open_idx in reversed(stack):
            open_line, open_indent, _ = braces[open_idx]
            close_line_str = ' ' * open_indent + '}\n'
            insert_at = len(result_lines)
            for i in range(open_line + 1, len(result_lines)):
                stripped = result_lines[i].strip()
                if stripped and not stripped.startswith('//'):
                    current_indent = len(result_lines[i]) - len(result_lines[i].lstrip())
                    if current_indent <= open_indent:
                        insert_at = i
                        break
            result_lines.insert(insert_at, close_line_str)

        # 5. Проверка первой строки (если там лишняя скобка)
        if result_lines and result_lines[0].strip() == '}':
            # Ищем минимальный отступ среди всех строк
            min_indent = min(
                (len(line) - len(line.lstrip()))
                for line in result_lines
                if line.strip() and not line.strip().startswith('//')
            )
            # Если первая скобка с отступом 0 и есть открывающие с таким же отступом – удаляем её
            first_indent = len(result_lines[0]) - len(result_lines[0].lstrip())
            if first_indent < min_indent:
                result_lines.pop(0)

        return result_lines

    def _missing_brace_suggestions(self, error: Dict, file_path: Path) -> List[Dict]:
        line_num = error.get("line", 0)
        return [{
            "type": "missing_brace",
            "line": line_num,
            "content": f"Compiler expects '}}' near line {line_num}. Review the surrounding block structure.",
            "patch": None,
        }]

    def _unexpected_closing_brace_suggestions(self, error: Dict, file_path: Path) -> List[Dict]:
        line_num = error.get("line", 0)
        return [{
            "type": "unexpected_closing_brace",
            "line": line_num,
            "content": f"Unexpected '}}' at line {line_num}. Check for missing opening brace or mismatched block.",
            "patch": None,
        }]

    def _missing_open_brace_suggestions(self, error: Dict, file_path: Path) -> List[Dict]:
        line_num = error.get("line", 0)
        return [{
            "type": "missing_open_brace",
            "line": line_num,
            "content": f"Add '{{' near line {line_num} to open the expected block.",
            "patch": None,
        }]

    def _indentation_mismatch_suggestions(self, error: Dict, file_path: Path) -> List[Dict]:
        msg = error.get("message", "")
        return [{
            "type": "indentation_mismatch",
            "line": error.get("line", 0),
            "content": f"Indentation mismatch: {msg}. Ensure consistent use of spaces/tabs.",
            "patch": None,
        }]

    def _unknown_prefix_suggestions(self, error: Dict, file_path: Path, line_num: int) -> List[Dict]:
        lines = self._read_file_lines(file_path)
        if 0 < line_num <= len(lines):
            return [{
                "type": "unknown_prefix",
                "line": line_num,
                "content": "The compiler reports an unknown prefix. This often means a missing space between tokens.",
                "patch": None,
            }]
        return []

    def _missing_semicolon_suggestions(self, error: Dict, file_path: Path, line_num: int) -> List[Dict]:
        lines = self._read_file_lines(file_path)
        if 0 < line_num <= len(lines):
            original = lines[line_num - 1]
            if not original.rstrip().endswith(';'):
                fixed = original.rstrip('\n').rstrip('\r') + ';\n'
                patch = (
                    f"--- a/main.rs\n"
                    f"+++ b/main.rs\n"
                    f"@@ -{line_num},1 +{line_num},1 @@\n"
                    f"-{original}"
                    f"+{fixed}"
                )
                return [{
                    "type": "missing_semicolon",
                    "line": line_num,
                    "content": f"Line {line_num} is missing a semicolon. Add ';' at the end.",
                    "patch": patch,
                }]
        return []

    @staticmethod
    def _read_file(file_path: Path) -> str:
        try:
            return file_path.read_text(encoding="utf-8")
        except Exception as e:
            logger.error("Failed to read %s: %s", file_path, e)
            return ""

    @staticmethod
    def _read_file_lines(file_path: Path) -> List[str]:
        return RustSyntaxHealer._read_file(file_path).splitlines(keepends=True)

    @staticmethod
    def _count_braces_safe(content: str) -> tuple:
        return count_braces_safe(content)